sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with docker file"
  - docker build -t briancjkim91/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true briancjkim91/docker-react-app npm run test -- --coverage

after_success:
  - scho "Test Success"
